// Build an idempotent SQL upsert of the 10 curated courses from
// data/research/*.json into public.courses (status = 'published'), and write
// it to supabase/seed/courses.sql. Apply that file to the Supabase project to
// seed. Re-running is safe: ON CONFLICT (id) DO UPDATE refreshes every field.
//
//   node scripts/seed-courses.mjs        # regenerate supabase/seed/courses.sql
//
// id = slug (text PK), so the marketing directory rows never collide with the
// app's UUID-keyed rows and the URL key is the primary key.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const researchDir = join(root, "data", "research");
const outDir = join(root, "..", "supabase", "seed");
mkdirSync(outDir, { recursive: true });

const SLUGS = [
  "torrey-pines-south", "torrey-pines-north", "bethpage-black", "pebble-beach",
  "tpc-sawgrass-stadium", "chambers-bay", "pinehurst-no-2", "bandon-dunes",
  "kiawah-island-ocean", "whistling-straits",
];

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const num = (v) => (v === null || v === undefined ? "null" : Number(v));
const jsonb = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const textArr = (arr) =>
  arr && arr.length
    ? `array[${arr.map((a) => q(a)).join(", ")}]::text[]`
    : "null";

const rows = SLUGS.map((slug) => {
  const c = JSON.parse(readFileSync(join(researchDir, `${slug}.json`), "utf8"));
  return `  (${[
    q(slug),                    // id
    q(c.name),
    q(c.city),
    q(c.state),
    q(c.country),
    num(c.holes_count),
    num(c.par_total),
    jsonb(c.par_per_hole),
    q(c.access_type === "resort" ? "resort" : c.access_type === "private" ? "private" : "public"), // type
    q("directory"),            // source
    q(slug),                    // slug
    q(c.address),
    q(c.zip),
    num(c.lat),
    num(c.lng),
    q(c.designer),
    num(c.year_opened),
    num(c.course_rating),
    num(c.slope_rating),
    jsonb(c.tees),
    q(c.website),
    q(c.phone),
    q(c.green_fee_tier),
    textArr(c.amenities),
    q(c.access_type),
    q("published"),            // status
  ].join(", ")})`;
}).join(",\n");

const sql = `-- Seed: 10 phase-1 directory courses. Generated by
-- marketing-site/scripts/seed-courses.mjs from data/research/*.json.
-- Idempotent: re-running refreshes every field from the curated JSON.
insert into public.courses (
  id, name, city, state, country, holes_count, par_total, par_per_hole,
  type, source, slug, address, zip, lat, lng, designer, year_opened,
  course_rating, slope_rating, tees, website, phone, green_fee_tier,
  amenities, access_type, status
) values
${rows}
on conflict (id) do update set
  name = excluded.name,
  city = excluded.city,
  state = excluded.state,
  country = excluded.country,
  holes_count = excluded.holes_count,
  par_total = excluded.par_total,
  par_per_hole = excluded.par_per_hole,
  type = excluded.type,
  source = excluded.source,
  slug = excluded.slug,
  address = excluded.address,
  zip = excluded.zip,
  lat = excluded.lat,
  lng = excluded.lng,
  designer = excluded.designer,
  year_opened = excluded.year_opened,
  course_rating = excluded.course_rating,
  slope_rating = excluded.slope_rating,
  tees = excluded.tees,
  website = excluded.website,
  phone = excluded.phone,
  green_fee_tier = excluded.green_fee_tier,
  amenities = excluded.amenities,
  access_type = excluded.access_type,
  status = excluded.status;
`;

writeFileSync(join(outDir, "courses.sql"), sql);
console.log(`Wrote supabase/seed/courses.sql (${rows.split("\n").length} rows)`);
